# Generated by Django 4.1 on 2022-11-30 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollchargedetails',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2032, 11, 17, 9, 54, 41, 510350)),
        ),
        migrations.AlterField(
            model_name='tollroaddetails',
            name='toll_charges_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.tollchargedetails'),
        ),
    ]
