# Generated by Django 4.1 on 2022-12-05 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_tollchargedetails_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tollchargedetails',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2032, 11, 22, 12, 11, 54, 592921)),
        ),
    ]
