# Generated by Django 4.1 on 2023-10-04 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_journeydetails_paid_alter_tollchargedetails_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollchargedetails',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2033, 9, 21, 8, 9, 39, 252163)),
        ),
    ]
