# Generated by Django 4.1 on 2022-08-22 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpn', models.CharField(max_length=12)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('lpn_class', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicledetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('street1', models.CharField(blank=True, max_length=75, null=True)),
                ('street2', models.CharField(blank=True, max_length=75, null=True)),
                ('street3', models.CharField(blank=True, max_length=75, null=True)),
                ('town_city', models.CharField(blank=True, max_length=75, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField()),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
