# Generated by Django 4.1 on 2022-08-23 08:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Ireland', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street1',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town_city',
            field=models.CharField(max_length=75),
        ),
    ]
