# Generated by Django 4.1 on 2022-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_userprofile_options_alter_uservehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
