# Generated by Django 4.1 on 2022-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_uservehicle_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
