# Generated by Django 4.1 on 2022-08-22 13:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('s_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address_1', models.CharField(max_length=75)),
                ('address_2', models.CharField(blank=True, max_length=75, null=True)),
                ('address_3', models.CharField(blank=True, max_length=75, null=True)),
                ('town_city', models.CharField(max_length=75)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpn', models.CharField(max_length=12)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('lpn_class', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('seq_no', models.IntegerField(default=1)),
                ('scrapped', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleownerdetails')),
            ],
        ),
    ]
