# Generated by Django 4.1 on 2022-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicledetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
