# Generated by Django 4.1 on 2022-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicledetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='end_date',
            field=models.DateTimeField(default='9999-12-31 23:59:59.999'),
        ),
    ]
