# Generated by Django 4.1 on 2022-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicledetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
