# Generated by Django 4.1 on 2022-11-30 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicledetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2032, 11, 17, 13, 13, 6, 762381)),
        ),
    ]
