# Generated by Django 4.1 on 2022-11-30 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicledetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2032, 11, 17, 14, 38, 10, 435334)),
        ),
    ]
