# Generated by Django 4.1 on 2022-12-05 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicledetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2032, 11, 22, 12, 11, 14, 813730)),
        ),
    ]
