# Generated by Django 4.1 on 2023-10-04 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_vehicledetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2033, 9, 21, 8, 9, 39, 249720)),
        ),
    ]
